project:
  type: website

website:
  title: "automatizar la publicaciÃ³n de reportes con Quarto y Github Actions"
  navbar:
    left:
      - href: index.qmd
        text: Taller
      - href: about.qmd
        text: "ðŸ‘‹ Somos MarÃ­a y Jesica"
      - href: slides.qmd
        text: Diapositivas
  favicon: "img/latinr-logo.png"

format:
  html:
    theme:
      - minty
      - brand

editor: visual

lang: es 
